export const ru = {
  code: {
    caption: "Сертификаты",
    captionShort: "Серт.",
    inputValue: "Ввести значение",
    create: "Создать",
    update: "Сохранить",
    search: "Поиск",
    loadedMessage: "Сертификаты загружены",
    completedMessage: "Сертификат завершен",
    sendConfirmationMessage: "Сертификат был отправлен, отправить повторно?",
    sentMessage: "Сертификат отправлен",
    sentProcessMessage: "Отправляем сертификат, ожидайте..",
    clear: "Очистить",
    digital: "электронный",
    printed: "физический"
  },
  order: {
    caption: "Заказы"
  },
  login: {
    error: 'Произошла ошибка, попробуйте позже',
    incorrect: 'Неправильный логин или пароль',
    login: 'Имя',
    password: 'Пароль',
    signIn: 'Войти',
    signOut: 'Выйти',
    caption: 'Вход',
    passwordRepeat: 'Повторите пароль',
    loginEmpty: "Имя пользователя не может быть пустым",
    emailWrong: "Электронная почта указана не верно"
  },
  templateCreate: {
    dataLoadedMsg: "Данные загружены",
    createdMsg: "Шаблон создан",
    updatedMsg: "Шаблон обновлен",
    offsetIsIncorrect: "Провертьте отступы",
    noImageSelected: "Выберите изображение",
    create: "Создать",
    update: "Сохранить",
    captionNew: "Новый шаблон",
    captionEdit: "Шаблон редактирование",
    name: "Название",
    verticalOffset: "Отступ сверху",
    horisontalOffset: "Отступ слева",
    content: "Изображение PNG",
    templateId: "Идентификатор",
  },
  codeCreate: {
    selectTemplatePlaceholder: "Выберите шаблон",
    template: "Шаблон",
    captionNew: "Новый сертификат",
    captionEdit: "Cертификат редактирование",
    userDataLoadedMsg: "Данные загружены",
    createdMsg: "Сертификат создан",
    updatedMsg: "Сертификат обновлен",
    balanceIsIncorrect: "Сумма должна быть больше нуля",
    completeIsIncorrect: "Дату завершения можно только удалить",
    templateNotSelected: "Выберите шаблон",
    messageOrCaptionEmpty: "Сообщение или заголовок сообщения пуст",
    emailWrong: "Почта должна быть либо пуста либо правильно заполнена",
    value: "Значение",
    name: "Кому имя",
    email: "Почта",
    telegram: "Telegram",
    whatsapp: "WhatsApp",
    balance: "Сумма",
    description: "Описание",
    created: "Создан",
    sent: "Отправлен",
    codeId: "Идентификатор",
    completed: "Завершен",
    message: "Сообщение",
    messageCaption: "Заголовок сообщения",
    messageDefault: "Здравствуйте, поздравляем! Кто-то сделал вам хороший подарок",
    messageCaptionDefault: "Подарочный сертификат от Vistelcorp"
  },
  userCreate: {
    userId: "Идентификатор",
    name: "Имя",
    login: "Login",
    passwordHash: "Пароль",
    description: "Описание",
    captionNew: "Новый пользователь",
    captionEdit: "Редактирование пользователя",
    userDataLoadedMsg: "Данные загружены",
    createdMsg: "Пользователь создан",
    updatedMsg: "Пользователь обновлен",
    lengthShouldBeMoreThan5Sym: "Login должен состоять мин. из 5 символов",
    lengthShouldBeMoreThan0Sym: "Имя не может быть пустым",
    wrongPassword: "Длина паролей должна составлять не менее 10 символов.\n" +
      "Пароли должны содержать по крайней мере одну заглавную букву, одну строчную букву, одну цифру и один специальный символ @$!%*#?",
    completed: "Завершен"
  },
  template: {
    caption: "Шаблоны",
    dataLoadedMsg: "Шаблоны загружены",
    create: "Создать",
    update: "Сохранить",
    search: "Поиск",
  },
  user: {
    caption: "Люди",
    authError: "Необходимо авторизоваться",
    email: "Email",
    dataLoadedMsg: "Пользователи загружены",
    create: "Добавить",
  },
  registration: {
    caption: 'Регистрация',
    name: 'ФИО',
    telegram: 'Телеграм',
    address: 'Адрес',
    button: "Зарегистрироваться",
    passwordsDoNotMatch: "Введённые пароли не совпадают",
    confirmTelegramMessage: "Для завершения регистрации необходимо подтвердить Телеграм по ссылке ниже",
    confirmed: "Телеграм подтверждён",
    userAgreementConfirm: "Продолжая пользоваться сайтом Вы принимаете пользовательское соглашение",
    userAgreement: "Пользовательское соглашение"
  },
  image: {
    cartActionDeleteIcon: "Удалить",
    cartActionEditIcon: "Редактировать",
    cartActionCompleteIcon: "Завершить",
    actionSendIcon: "Отправить",
    cartActionFavoriteIcon: "Добавить в избранное",
    cartProductImage: "Картинка с товаром",
  },
  currency: {
    RUB: "₽",
    USD: "$",
    EUR: "€",
    CNY: "¥",
  }
}

export default ru;