version: "3.5"
services:
  db:
    image: mariadb:10.3.9
    ports: # порт открыт только для проверки, должен быть закрыт на рабочей машине
      - '3306:3306'
    volumes:
      - ./tmpdb:/var/lib/mysql:rw
      - ../database/Docker/utf8.cnf:/etc/mysql/conf.d/custom.cnf
      - ../database/MigrationsWithEnv:/docker-entrypoint-initdb.d:ro # раскомментировать для загрузки Migrations
    env_file: .env # здесь секреты, структуру можно посмотреть в _env
    restart: unless-stopped
    networks:
      - wire

  back:
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    ports:
      - '8080:80' # порт открыт только для проверки, должен быть закрыт на рабочей машине
    env_file: .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
      pdf:
        condition: service_started
    networks:
      - wire

  ml: # обработка данных с карт
    build:
      context: ../../ml_part # ожидаем что проект ml_part лежит на одном уровне с back
    restart: unless-stopped
    env_file: .env
    networks:
      - wire
  
  front: # статические файлы и проброс API
    depends_on:
      - back
    build:
      context: ../../front # ожидаем что проект front лежит на одном уровне с back
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - wire

networks:
  wire:
    driver: bridge

